### ISSUE TITLE
Module: UTXO

### ISSUE THREAD

**Issue by LaurentMontBlanc** [planetmint/planetmint#361]
## Description:
The UTXO module is responsible for the following:
 - storing inputs and outputs
 - updating the UTXO set
 - validating inputs against consumed outputs

## Tasks:
- [ ] create input type
- [ ] create output type
- [ ] implement storeOutput / getOutput
- [ ] implement storeInput / getInput
- [ ] implement updateUtxoSet
- [ ] implement validateInputs

**Comment by LaurentMontBlanc** [comment]
removing this from sprint for now as other topics got priority
