### ISSUE TITLE
refactor UTXO handling

### ISSUE THREAD

**Issue by LaurentMontBlanc** [planetmint/planetmint#366]
# Description
An [analysis](https://www.notion.so/riddlecode/Map-of-Planetmint-fdeeb219052a4ba0a1c5cce9f1fa432f) of the current UTXO showed that the handling of outputs is overly complicated and can be simplified to increase readability.

## Tasks:
- [x] update TX storing to utilize UTXO space
- [x] update UTXO querying 
- [x] update input validation
- [x] remove deprecated code
- [x] update test suite
- [x] update Map of Planetmint
